{% set python_min = '3.10' %}
{% set name = "jax" %}
{% set version = "0.4.35" %}
# Not declared in the metadata but essential to this package.
# update minimum from https://github.com/google/jax/blob/main/jax/version.py
{% set minimum_jaxlib_version = "0.4.34" %}


package:
  name: jax
  version: {{ version }}

source:
  # only pull source after PyPI release.
  url: https://pypi.org/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: c0c986993026b10bf6f607fecb7417377460254640766ce40f1fef3fd139c12e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - opt-einsum
    - scipy >=1.10
    - ml_dtypes >=0.4.0
    - jaxlib >=0.4.34,<=0.4.35
    - importlib-metadata >=4.6
  run_constrained:
    - cudnn >=9.2.1.18

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip
    # test with the declared minimum jaxlib
    - jaxlib =={{ minimum_jaxlib_version }}
    - python {{ python_min }}

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
    - ngam
